
environment:
  psg_api_key: 
    secure: e3uoVHqaTTa+BqEphKfjGYLXG4OXTmAktNhbWXAD+ZT6BD94F0dqabjfwbcKk14t

build_script:

# copy module contents
- ps: New-Item pglet -Type Directory | Out-Null
- ps: Copy-Item -Path *.psd1 -Destination pglet
- ps: Copy-Item -Path *.psm1 -Destination pglet

# publish module
- ps: |
    if ($env:APPVEYOR_REPO_TAG -eq 'true') {

      # version
      $ver = $env:APPVEYOR_REPO_TAG_NAME
      if ($ver.StartsWith('v')) { $ver = $ver.Substring(1) }

      # prerelease moniker
      $idx = $ver.indexOf('-')
      if ($idx -ne -1) {
        $prerelease = $ver.Substring($idx + 1)
        $ver = $ver.Substring(0, $idx)
      }
      (Get-Content pglet\pglet.psd1).replace("ModuleVersion     = '0.1.0'", "ModuleVersion = '$ver'") | Set-Content pglet\pglet.psd1
      if ($prerelease) {(Get-Content pglet\pglet.psd1).replace("# Prerelease = 'beta'", "Prerelease = '$prerelease'") | Set-Content pglet\pglet.psd1}
      Publish-Module -Path $env:APPVEYOR_BUILD_FOLDER\pglet -NuGetApiKey $env:psg_api_key
    }

test: off